[workspace]
members = ["dust-cli", "dust-compiler", "dust-vm"]
default-members = ["dust-cli", "dust-compiler", "dust-vm"]
resolver = "2"

[workspace.package]
authors = ["Jeff Anderson"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/solaeus/dust"
version = "0.5.0"
edition = "2024"

[profile.release]
opt-level = 3
debug = false
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = true
codegen-units = 1
rpath = false

[profile.perf]
inherits = "release"
debug = true
strip = "none"
