[package]
name = "dust-lang"
description = "Data-Oriented Programming Language"
version = "0.3.2"
repository = "https://github.com/tree-sitter/tree-sitter-dust"
edition = "2018"
license = "MIT"

[[bin]]
name = "dust"
path = "src/main.rs"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.4.4", features = ["derive"] }
comfy-table = "7.0.1"
csv = "1.2.2"
git2 = "0.18.1"
json = "0.12.4"
rand = "0.8.5"
rayon = "1.8.0"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }
rustyline = { version = "12.0.0", features = ["derive", "with-file-history"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
toml = "0.8.1"
tree-sitter = "0.20.10"

[build-dependencies]
cc = "1.0"
