[package]
name = "dust"
description = "Data-Oriented Programming Language"
version = "0.3.0"
repository = "https://github.com/tree-sitter/tree-sitter-dust"
edition = "2018"
license = "MIT"
include = ["tree_sitter_parser"]

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.31"
clap = { version = "4.4.4", features = ["derive"] }
comfy-table = "7.0.1"
csv = "1.2.2"
eframe = "0.22.0"
egui = "0.22.0"
egui_extras = "0.22.0"
git2 = "0.18.1"
json = "0.12.4"
rand = "0.8.5"
rayon = "1.8.0"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }
rustyline = { version = "12.0.0", features = ["derive", "with-file-history"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sysinfo = "0.29.10"
toml = "0.8.1"
trash = "3.0.6"
tree-sitter = "0.20.10"

[build-dependencies]
cc = "1.0"
