[package]
name = "dust-lang"
description = "General purpose programming language"
version = "0.4.0"
repository = "https://git.jeffa.io/jeff/dust.git"
edition = "2021"
license = "MIT"
authors = ["Jeff Anderson"]

[[bin]]
name = "dust"
path = "src/main.rs"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.4.4", features = ["derive"] }
csv = "1.2.2"
egui = "0.24.1"
eframe = { version = "0.24.1", default-features = false, features = [
    "accesskit",
    "default_fonts", 
    "glow",   
    "persistence",
] }
libc = "0.2.148"
log = "0.4.20"
rand = "0.8.5"
rayon = "1.8.0"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }
rustyline = { version = "12.0.0", features = ["derive", "with-file-history"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
toml = "0.8.1"
tree-sitter = "0.20.10"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

[build-dependencies]
cc = "1.0"
