[workspace]
members = ["dust-lang", "dust-shell"]
default-members = ["dust-lang"]
resolver = "2"

[workspace.package]
authors = ["Jeff Anderson"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://git.jeffa.io/jeff/dust.git"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
