[package]
name = "dust-lang"
description = "General purpose programming language"
version = "0.5.0"
repository = "https://git.jeffa.io/jeff/dust.git"
edition = "2021"
license = "MIT"
authors = ["Jeff Anderson"]

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[dependencies]
ariadne = { version = "0.4.0", features = ["auto-color"] }
chumsky = { version = "1.0.0-alpha.6", features = ["pratt", "label"] }
clap = { version = "4.5.2", features = ["derive"] }
colored = "2.1.0"
env_logger = "0.11.3"
log = "0.4.21"
stanza = "0.5.1"
