//! Representation of a Dust function.
//!
//! Prototypes are generated by the compiler (specifically, the emitter) and are used by the virtual
//! machine to execute Dust functions within a program. Dust's prototypes are not self-contained,
//! instructions refer directly to the program's global constant pool and prototype list. This is a
//! key diversion from Lua's design (which is a major influence for Dust), in which each prototype
//! contains its own lists of constants and nested prototypes.
use std::{
    borrow::Borrow,
    collections::HashSet,
    fmt::{self, Debug, Display, Formatter},
    ops::Index,
    vec,
};

use rustc_hash::FxBuildHasher;
use serde::{Deserialize, Serialize};

use crate::{
    dust_type::DustType,
    instruction::{CallArgument, Instruction},
};

/// Compiled representation of a Dust function.
#[derive(Clone, Debug, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Prototype {
    pub(crate) instructions: Vec<Instruction>,
    pub(crate) call_arguments: Vec<CallArgument>,
    pub(crate) drops: Vec<u16>,
    pub(crate) return_type: DustType,
    pub(crate) i32_register_count: u16,
    pub(crate) i64_register_count: u16,
    pub(crate) f64_register_count: u16,
    pub(crate) pointer_register_count: u16,
}

impl Prototype {
    pub(crate) fn placeholder() -> Self {
        Self {
            instructions: Vec::new(),
            call_arguments: Vec::new(),
            drops: Vec::new(),
            return_type: DustType::Unit,
            i32_register_count: 0,
            i64_register_count: 0,
            f64_register_count: 0,
            pointer_register_count: 0,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct PrototypeList {
    prototypes: Vec<Prototype>,
}

impl PrototypeList {
    pub(crate) fn new() -> Self {
        Self {
            prototypes: Vec::new(),
        }
    }

    pub fn len(&self) -> usize {
        self.prototypes.len()
    }

    pub fn is_empty(&self) -> bool {
        self.prototypes.is_empty()
    }

    pub fn as_vec(&self) -> &Vec<Prototype> {
        &self.prototypes
    }

    pub fn as_slice(&self) -> &[Prototype] {
        &self.prototypes
    }

    pub fn iter(&self) -> impl Iterator<Item = &Prototype> {
        self.prototypes.iter()
    }

    pub fn reserve_slot(&mut self) -> PrototypeId {
        let id = PrototypeId(self.prototypes.len() as u16);

        self.prototypes.push(Prototype::placeholder());

        id
    }

    pub fn set_slot(&mut self, id: PrototypeId, prototype: Prototype) {
        assert!(
            (id.0 as usize) < self.prototypes.len(),
            "Logic error: misuse of prototype ID {id}. When used correctly, prototype IDs are always\
            reserved before being set, so this should never happen.",
        );

        self.prototypes[id.0 as usize] = prototype;
    }
}

pub struct PrototypeCompileInfo {
    pub compile_order: Vec<PrototypeId>,
    pub argument_counts: Vec<u16>,
    pub recursive_calls: HashSet<(u16, u16), FxBuildHasher>,
}

impl Borrow<[Prototype]> for PrototypeList {
    fn borrow(&self) -> &[Prototype] {
        &self.prototypes
    }
}

impl Index<usize> for PrototypeList {
    type Output = Prototype;

    fn index(&self, index: usize) -> &Self::Output {
        &self.prototypes[index]
    }
}

impl Index<PrototypeId> for PrototypeList {
    type Output = Prototype;

    fn index(&self, index: PrototypeId) -> &Self::Output {
        &self.prototypes[index.0 as usize]
    }
}

impl IntoIterator for PrototypeList {
    type Item = Prototype;
    type IntoIter = vec::IntoIter<Prototype>;

    fn into_iter(self) -> Self::IntoIter {
        self.prototypes.into_iter()
    }
}

#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord, Hash)]
pub struct PrototypeId(#[cfg(test)] pub(crate) u16, #[cfg(not(test))] u16);

impl PrototypeId {
    pub(crate) const MAIN: Self = Self(0);

    pub fn index(self) -> u16 {
        self.0
    }

    pub fn index_usize(self) -> usize {
        self.0 as usize
    }
}

impl Display for PrototypeId {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        write!(f, "proto_{}", self.0)
    }
}
