//! Compiled representation of a function.
use serde::{Deserialize, Serialize};
use smallvec::SmallVec;

use crate::instruction::{Instruction, OperandType};

/// Compiled representation of a function.
///
/// Prototypes are generated by the compiler and used by the virtual machine to execute functions.
#[derive(Clone, Debug, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Prototype {
    pub(crate) instructions: Vec<Instruction>,
    pub(crate) return_types: OperandType::SmallVec,
    pub(crate) register_count: u16,
    pub(crate) argument_count: u16,
}

impl Prototype {
    pub(crate) fn placeholder() -> Self {
        Self {
            instructions: Vec::new(),
            return_types: SmallVec::new(),
            register_count: 0,
            argument_count: 0,
        }
    }
}
