[package]
name = "dust-cli"
description = "Command line interface for the Dust programming language"
authors = ["Jeff Anderson"]
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "dust"
path = "src/main.rs"

[dependencies]
basic-toml = "0.1.9"
clap = { version = "4.5.14", features = [
    "cargo",
    "color",
    "derive",
    "help",
    "wrap_help",
] }
color-print = "0.3.7"
dust-lang = { path = "../dust-lang" }
postcard = "1.0.10"
serde_json = "1.0.133"
toml = "0.8.20"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
