[package]
name = "dust-cli"
description = "Command line interface for the Dust programming language"
authors = ["Jeff Anderson"]
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "dust"
path = "src/main.rs"

[features]
mimalloc = ["dust-compiler/mimalloc"]

[dependencies]
clap = { version = "4.5.59", features = [
    "cargo",
    "color",
    "derive",
    "env",
    "help",
    "wrap_help",
] }
colored = "3.1.1"
crossterm = "0.29.0"
dust-compiler = { path = "../dust-compiler" }
dust-vm = { path = "../dust-vm" }
ron = "0.12.0"
toml = "0.9.12"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "time"] }
