[package]
name = "dust-lang"
description = "Dust programming language library"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
jit = ["cranelift", "cranelift-jit", "cranelift-module", "cranelift-native"]
mimalloc = []


[dependencies]
annotate-snippets = "0.12.12"
bumpalo = { version = "3.20.1", features = ["boxed", "collections"] }
clap = { version = "4.5.59", features = ["env"] }
cranelift = { version = "0.126.2", optional = true }
cranelift-jit = { version = "0.126.2", optional = true }
cranelift-module = { version = "0.126.2", optional = true }
cranelift-native = { version = "0.126.2", optional = true }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel", "nightly"] }
crossbeam-channel = "0.5.15"
getrandom = "0.3" # Indirect dependency, for WASM builds
indexmap = { version = "2.13.0", features = ["serde"] }
lexical-core = { version = "1.0.6", features = ["format"] }
memmap2 = "0.9.10"
mimalloc = "0.1.48"
rand = "0.9.2"
ratatui = "0.30.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.149"
smallvec = { version = "1.15.1" }
tracing = "0.1.44"
unicode-ident = "1.0.24"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "lexer"
harness = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "compiler"
harness = false

# [[bench]]
# name = "addictive_addition"
# harness = false

# [[bench]]
# name = "addictive_calling"
# harness = false

# [[bench]]
# name = "fibonacci"
# harness = false

# [[bench]]
# name = "threads"
# harness = false
