disallowed-macros = [
    "core::panic",
    "core::unimplemented",
    "core::unreachable",
    "core::todo",
]
disallowed-methods = [
    "std::option::Option::expect",
    "std::option::Option::unwrap",
    "std::result::Result::expect",
    "std::result::Result::unwrap",
]
